export enum TypeNames {
  HANDLE_CHANGE_THEME_COLORS = 'HANDLE_CHANGE_THEME_COLORS',
  HANDLE_CHANGE_DEFAULT_THEMES_ARR = 'HANDLE_CHANGE_DEFAULT_THEMES_ARR',
  HANDLE_CHANGE_TWO_COLOR_COLUMN = 'HANDLE_CHANGE_TWO_COLOR_COLUMN',
  HANDLE_CHANGE_ONE_COLOR_COLUMN = 'HANDLE_CHANGE_ONE_COLOR_COLUMN'
}

