export enum TypeNames {
  HANDLE_CHANGE_ANONYMOUS_STATUS = 'HANDLE_CHANGE_ANONYMOUS_STATUS',
  HANDLE_CHANGE_LOGIN_STATUS = 'HANDLE_CHANGE_LOGIN_STATUS',
  HANDLE_CHANGE_ERROR_STATUS = 'HANDLE_CHANGE_ERROR_STATUS',
  HANDLE_CHANGE_ERROR_MESSAGE = 'HANDLE_CHANGE_ERROR_MESSAGE'
}
