
export const ADD_NEW_PAKEEP = 'ADD_NEW_PAKEEP';
export const CHANGE_PAKEEP_COLUMNS = 'CHANGE_PAKEEP_COLUMNS';
export const CHANGE_TWO_PAKEEP_COLUMNS = 'CHANGE_TWO_PAKEEP_COLUMNS';
export const ADD_DATE_TO_PAKEEP = 'ADD_DATE_TO_PAKEEP';
export const IS_MENU_OPEN = 'IS_MENU_OPEN';
export const SCROLL_DIRECTION = 'SCROLL_DIRECTION';



